### ISSUE TITLE
Corrección Instalación Ubuntu

### ISSUE THREAD

**Issue by pwall2222** [AzorinREY/Instalacion_de_Ubuntu.md#1]
# Correción

## Trata os 13 puntos?

- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [x] 6
- [x] 7
- [x] 8
- [ ] 9
- [ ] 10
- [ ] 11
- [ ] 12

## Os 13 puntos son correctos?

- [x] 1
- [x] 2
- [x] 3
- [x] 4
- [x] 5
- [x] 6
- [ ] 7 - Non localizou o ficheiro de configuración
- [x] 8

## Markdown y commits

- Mais de un H1 (#) deberian ser H2 (##) -0.1

## Opinión

O markdown esta bastante ben feito a pesar de ter uns cantos erros de headers e ao mellor demasiadas listas está bastante ben en xeral. A unica queixa que teño e que os archivos das imaxes non teñen nomes descriptivos.

## Puntuación

1	Puntos por ter todas as tareas
2.5	Pola correción das tareas
0.9	Markdown
2	Por opinión persoal

Nota total: 6.4

**Comment by CristianMellaH** [comment]
# Corección(AzorinREY)
## Trata os 13 puntos e están correctos

. Fai unha instalación mínima de Ubuntu 20 nunha VM de VirtualBox .
. Actualiza o sistema.
. Instala curl.
. Instala a shell fish.
. Instala pure, o plugin da shell fish
. Configura fish como a shell por defecto e localiza o ficheiro de configuración no que se produce o cambio.
. Instala fisher (utilidade para instalar/desinstalar plugins de fish) usando curl.
. Instala a versión máis actualizada de git (non vale a que ven por defecto nos repos de Ubuntu)
. Documenta, incluindo capturas de pantalla, todo o proceso nun repositorio git subido a Github.

Todos esos puntos están correctos e ben explicados con todo luxo de detalle (9 puntos en total)
Sin embargo faltan:
1. A configuración global de `Git`
2. A xeración de chaves SSH e engadilas.
3. Editar o archivo `.gitconfig` e añadir o código necesario.
4. Clona o repositorio no que esteas a documentar todo este proceso na máquina virtual. PISTA git clone <repo-ssh>
  
Polo que restaría en función da "importancia" dos puntos non realizados:
 -0,5 polas chaves. (-0,5 porque sen elas, non nos podemos identificar en nosa máquina en GIT)
 -0,5 pola configuración. (-0,5 porque sen configuralo, non vai)
 -0,05 por `.gitconfig` (-0,05 porque non habería tampouco ningún problema de non realizar este paso fóra do ámbito da tarefa)
 -0,05 polo `git clone` (-0,05 porque non está replicado en ningunha máquina secundaria, sen embargo na máquina local está) 
  Quedando un total de -1,10 puntos.
  
  Tendo en conta que os seguintes 3 puntos son pola boa explicación dos mesmos, aos puntos que faltan habería que restarlle máis por enriba.
  **Sen embargo** vin que o traballou e que lle puxo empeño (moito máis ca min) a explicar cada punto, entón queda como está.
  
  ## Markdown e commits correctos 
  O markdown está ben e a inserción das imaxes pequenas con botóns de VirtualBox están colocadas correctamente (o único que non me gusta son os puntos que aparecen á esquerda das imaxes, pero non son quen de quitar nada por eso).
  Os commits están correctos e fan sentido (superan con creces o mínimo "establecido" en clase de 25 commits)
  
  Facendo reconto da puntuación total que se consigueu, temos un `5,9` ( 7 puntos do total entre os 3 criterios menos 1,10)
  
  ### Puntos a valorar baixo meu criterio
  
  1. O ben que está todo explicado tanto a instalación da máquina virtual como a configuración interna (fish, pure, curl...)
  2. A existencia dun `Table of contents` que como tamén expliquei con pwall2222, utilizoo como un punto de regalo para quen o ten, xa que tampouco aparece coma un paso necesario no cumprimento da tarefa.
  **Neste caso, non se obtén ese punto.**
  3. Sendo deste traballo a dedicación a explicar os pasos o punto máis forte que atopo (e porque faltan varios puntos da tarefa) necesitaría algo de "axuda para obter un criterio para un tercer punto engadido.
  (todo se fala en clase, con unha boa ofrenda a Thor [EU] para que poida fuchicar no seu coche, toda nota se pode subir) 

Nota final: `5,9` + `1` = `6,9`
